name: Deploying docker images to ECR
on: [ push ]
jobs:
  build:
    runs-on: ghrunner-test

    steps:
      - uses: actions/checkout@v5

      - name: Build docker image
        run: |
          

          aws ecr-public get-login-password --region ap-south-1 | docker login --username AWS --password-stdin public.ecr.aws/h1j4a0g4

          docker build -f Dockerfile -t roboshop/frontend .

          docker tag roboshop/frontend:latest public.ecr.aws/h1j4a0g4/roboshop/frontend:latest

          docker push public.ecr.aws/h1j4a0g4/roboshop/frontend:latest
