name: Deploying docker images to ECR
on: [ push ]
jobs:
  build:
    runs-on: ghrunner-test

    steps:
      - uses: actions/checkout@v5

      - name: Build docker image
        run: |
          working-dir=pwd
          echo "$pwd"

