name: Deploying docker images to ECR
on: [ push ]
jobs:
  build:
    runs-on: ghrunner-test

    steps:
      - uses: actions/checkout@v5

      - name: Build docker image
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
          
      - name: Login to ECR Public and Build Image
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/h1j4a0g4      
      - name: Build, Tag, Push
        run: |
          sudo docker build -t frontend .
  
          sudo docker tag frontend:latest public.ecr.aws/h1j4a0g4/frontend:latest

          sudo docker push public.ecr.aws/h1j4a0g4/frontend:latest

          sudo docker system prune -y

